### ISSUE TITLE
Remove inner structure

### ISSUE THREAD

**Issue by rsy6318** [jianglongye/gifs#3]
Hi, I have noticed that in your paper, 'For watertight shapes, we use the common training/test split from 3D-R2N2 [14] and the processed watertight meshes from DISN [66].'
But I did not find the code in DISN to remove the inner structure of the model. Could you please provide these codes or corresponding links?

**Comment by rsy6318** [comment]
I just found a similar code in Occupancy Network, is it the same?
https://github1s.com/autonomousvision/occupancy_networks/blob/HEAD/scripts/dataset_shapenet/build.sh

**Comment by jianglongye** [comment]
Actually, DISN provides the processed data [here](https://github.com/Xharlie/DISN#prepare-the-sdf-ground-truth-and-the-marching-cube-reconstructed-ground-truth-models), we can directly download it.

**Comment by rsy6318** [comment]
Thanks for reply !
