### ISSUE TITLE
How to calculate CD median?

### ISSUE THREAD

**Issue by Wi-sc** [jianglongye/gifs#4]
Hi @jianglongye ,

Thx for your impressive work and codes. I just want to reproduce your results so I want to clarify how to get the CD median in your paper.

From the definition of CD, suppose we have 10k prediction points **p** and 10k ground-truth points **q**, we can get 20k **p-to-q** and **q-to-p** distance. Are you get the median from the 20k distances? Or do you get the mean of two medians from **p-to-q** and **q-to-p**?

Thanks again.

**Comment by jianglongye** [comment]
I took the mean of two medians from p-to-q and q-to-p as the CD median.
